title: "INDIAN STUDENTS AND RESEARCHERS IN KOREA (ISRK)"
email: "isrk.website@gmail.com"
youtube: "https://www.youtube.com/channel/UCVtezYzITvXCpl54UPPIJTQ/streams"
whatsapp: 
description: "Empowering Indian students and researchers in Korea to thrive academically, professionally, and personally."
baseurl: "/isrk.github.io" # the subpath of your site
url: "https://Aditi1612.github.io" # your GitHub Pages base URL

# Build settings
markdown: kramdown
theme: minima
permalink: /:categories/:year/:month/:day/:title.html
paginate: 5
