title: "INDIAN STUDENTS AND RESEARCHERS IN KOREA (ISRK)"
email: "isrk.association@gmail.com"
youtube: "https://www.youtube.com/channel/UCVtezYzITvXCpl54UPPIJTQ/streams"
whatsapp: 
description: "Empowering Indian students and researchers in Korea to thrive academically, professionally, and personally."
baseurl: ""
url: "https://www.isrk.in"

# Build settings
markdown: kramdown
theme: minima
permalink: /:categories/:year/:month/:day/:title.html
paginate: 5
